sensor:
  input_source: leap_motion
  webcam:
    index: 0
  camera2table:
  - - 1.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - -1.0
  - - 0.0
    - 1.0
    - 0.0
  rerun_enabled: false
retargeting:
  mode: single_left
  left:
    urdf_path: allegro_hand/allegro_hand_left.urdf
    add_dummy_free_joint: true
    optimizer:
      type: joint
      params:
        low_pass_alpha: 1
  right: {}
simulation:
  mj_xml_path: /home/lab/Documents/teleop_scene_left_077_rubiks_cube
  control_hand: left
  root_ctrl_indices:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  finger_ctrl_indices:
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 10
  - 11
  - 12
  - 13
  - 6
  - 7
  - 8
  - 9
  root_position_offset:
  - 0.2
  - 0.0
  - -0.6
  root_rotation_offset_euler_zyx:
  - 0.0
  - 0.0
  - 0.0
  joint_indices:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  camera_names: []
  control_rate_hz: 60.0
  mocap:
    wrist_mocap: false
    mocap_body_name: null
    mocap_id: null

